export const userError = {
  EMAIL_ALREADY_USED: {},
  NO_DEFAULT_ROLE: {},
  USER_NOT_FOUND: {},
  ACTIVATE_ACCOUNT_TOKEN_EXPIRED: {},
  ACTIVATE_ACCOUNT_TOKEN_IS_REQUIRED: {},
  PASSWORD_RESET_TOKEN_EXPIRED: {},
  VERIFY_EMAIL_TOKEN_IS_REQUIRED: {},
  VERIFY_EMAIL_TOKEN_EXPIRED: {},
}
