version: '3'
services:
  # PostgreSQL
  postgres:
    image: 'postgres:10'
    container_name: 'stock-management-api-server-postgres'
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DATABASE}'
  # MailHog
  mailhog:
    image: 'mailhog/mailhog'
    container_name: 'stock-management-api-server-mailhog'
    ports:
      - '587:1025'
      - '3001:8025'
  # Adminer
  adminer:
    image: 'adminer:4.7'
    container_name: 'stock-management-api-server-adminer'
    links:
      - 'postgres:postgres'
    ports:
      - '3002:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DESIGN: 'pappu687'
